const createService = ({ name, image, useCaseImages, useCases, eyebrow, headline, description, benefits, steps }) => ({
  name,
  image,
  useCaseImages,
  useCases,
  eyebrow,
  headline,
  description,
  what: `${name} gives businesses, service partners, and customers a secure digital workflow for ${description.charAt(0).toLowerCase()}${description.slice(1)} The guided experience reduces manual effort, provides clear status visibility, and keeps every step organized.`,
  benefits,
  steps,
});

const utilityImages = ["/images/payment-solutions/services/india-utility-service.png", "/images/payment-solutions/services/electricity.jpg", "/images/payment-solutions/services/water.jpg"];
const verificationImages = ["/images/payment-solutions/services/india-digital-service.png", "/images/payment-solutions/services/digital-verification.jpg", "/images/payment-solutions/pan-card.jpg"];
const loanImages = ["/images/payment-solutions/services/india-loan-consultation.png", "/images/payment-solutions/services/home-loan.jpg", "/images/payment-solutions/services/business-loan.jpg"];

export const paymentSolutionsData = {
  payin: {
    name: "PayIn",
    image: "/images/payment-solutions/payin.jpg",
    useCaseImages: ["/images/payment-solutions/use-cases/payin-marketplace.jpg", "/images/payment-solutions/use-cases/payin-subscription.jpg", "/images/payment-solutions/use-cases/payin-retail.jpg"],
    useCases: ["Online marketplaces", "Subscription businesses", "Retail collections"],
    eyebrow: "Accept payments without friction",
    headline: "Smart PayIn Solutions for Faster Collections",
    description: "Collect customer payments securely through UPI, cards, net banking, and other popular modes with one reliable integration.",
    what: "PayIn is a digital collection solution that enables businesses to accept and verify customer payments in real time. It brings multiple payment modes into one streamlined flow, helping you improve success rates, simplify reconciliation, and deliver a smooth checkout experience.",
    benefits: ["Multiple payment modes", "Real-time payment status", "Automated reconciliation", "Secure API integration"],
    steps: ["Business Integrates API", "Customer Makes Payment", "Payment Verification", "Real-Time Settlement", "Transaction Report"],
  },
  payout: {
    name: "Payout",
    image: "/images/payment-solutions/services/business-loan.jpg",
    useCaseImages: ["/images/payment-solutions/services/india-digital-service.png", "/images/payment-solutions/services/business-loan.jpg", "/images/payment-solutions/services/digital-verification.jpg"],
    useCases: ["Vendor payments", "Salary disbursals", "Customer refunds"],
    eyebrow: "Move money with confidence",
    headline: "Instant, Secure Payouts at Business Scale",
    description: "Disburse funds to bank accounts and UPI IDs through a fast, trackable, API-led payout platform.",
    what: "Payout is a digital disbursement solution for sending money to vendors, employees, partners, and customers. A single dashboard and API help businesses automate bulk transfers, monitor every transaction, and reduce manual payment operations.",
    benefits: ["Instant fund transfers", "Bulk payout support", "Live status tracking", "Role-based security"],
    steps: ["Business Integrates API", "Beneficiary Is Added", "Transfer Is Initiated", "Bank Confirms Payout", "Report Is Generated"],
  },
  dmt: {
    name: "DMT",
    image: "/images/payment-solutions/services/digital-verification.jpg",
    useCaseImages: ["/images/payment-solutions/services/dmt-retail-agent-networks.png", "/images/payment-solutions/services/dmt-assisted-banking-points.png", "/images/payment-solutions/services/dmt-rural-money-transfers.png"],
    useCases: ["Retail agent networks", "Assisted banking points", "Rural money transfers"],
    eyebrow: "Domestic transfers made simple",
    headline: "Reliable Domestic Money Transfer Services",
    description: "Enable assisted domestic money transfers with secure beneficiary management and instant transaction updates.",
    what: "Domestic Money Transfer (DMT) allows customers to send funds to bank accounts across India through an assisted agent network. Built-in verification, beneficiary controls, and transaction reporting make every transfer easy to manage.",
    benefits: ["Wide bank coverage", "Fast beneficiary verification", "Instant transaction updates", "Agent-friendly platform"],
    steps: ["Agent Verifies Customer", "Beneficiary Is Selected", "Transfer Is Submitted", "Bank Processes Funds", "Receipt Is Generated"],
  },
  aeps: {
    name: "AEPS",
    image: "/images/payment-solutions/aeps.jpg",
    useCaseImages: ["/images/payment-solutions/use-cases/aeps-correspondent.jpg", "/images/payment-solutions/use-cases/aeps-retail.jpg", "/images/payment-solutions/use-cases/aeps-inclusion.jpg"],
    useCases: ["Banking correspondents", "Retail service points", "Financial inclusion networks"],
    eyebrow: "Aadhaar-enabled banking access",
    headline: "Bring Essential Banking Closer with AEPS",
    description: "Offer Aadhaar-based cash withdrawal, balance enquiry, and mini statement services through a secure agent platform.",
    what: "The Aadhaar Enabled Payment System (AEPS) lets customers access basic banking services using Aadhaar authentication at an authorized agent point. It expands financial access while giving operators real-time visibility into every request.",
    benefits: ["Aadhaar-based authentication", "Cash withdrawal support", "Balance and mini statements", "Real-time agent reports"],
    steps: ["Agent Selects Service", "Customer Shares Aadhaar", "Biometric Is Verified", "Bank Processes Request", "Receipt Is Generated"],
  },
  "bus-booking": {
    name: "Bus Booking",
    image: "/images/payment-solutions/bus-booking.jpg",
    useCaseImages: ["/images/payment-solutions/use-cases/bus-agency.jpg", "/images/payment-solutions/use-cases/bus-agent.jpg", "/images/payment-solutions/use-cases/bus-portal.jpg"],
    useCases: ["Travel agencies", "Retail booking agents", "Consumer travel portals"],
    eyebrow: "Travel booking on one platform",
    headline: "A Faster Way to Search and Book Bus Tickets",
    description: "Give customers access to routes, operators, seats, and booking confirmation through a simple digital experience.",
    what: "Our Bus Booking solution connects travel businesses and agents with bus inventory through a unified platform. Customers can compare trips, choose seats, pay securely, and receive booking details without switching systems.",
    benefits: ["Real-time route search", "Interactive seat selection", "Multiple operator access", "Instant booking confirmation"],
    steps: ["Customer Searches Route", "Trip and Seat Are Selected", "Passenger Details Are Added", "Payment Is Confirmed", "Ticket Is Issued"],
  },
  "bbps-bill-payments": {
    name: "BBPS Bill Payments",
    image: "/images/payment-solutions/bbps.jpg",
    useCaseImages: ["/images/payment-solutions/use-cases/bbps-counter.jpg", "/images/payment-solutions/use-cases/bbps-agents.jpg", "/images/payment-solutions/use-cases/bbps-app.jpg"],
    useCases: ["Utility bill counters", "Agent networks", "Consumer payment apps"],
    eyebrow: "One place for everyday bills",
    headline: "Unified and Convenient BBPS Bill Payments",
    description: "Enable secure bill discovery and payment across electricity, water, gas, broadband, insurance, and more.",
    what: "BBPS Bill Payments provide an interoperable way to fetch and pay recurring bills across supported categories. Businesses and agents can offer customers a consistent payment experience with instant confirmation and organized transaction records.",
    benefits: ["Multiple biller categories", "Instant bill fetch", "Secure payment confirmation", "Centralized reporting"],
    steps: ["Customer Selects Biller", "Bill Details Are Fetched", "Customer Confirms Amount", "Payment Is Processed", "Receipt Is Generated"],
  },
  recharges: {
    name: "Recharges",
    image: "/images/payment-solutions/recharges.jpg",
    useCaseImages: ["/images/payment-solutions/use-cases/recharge-mobile.jpg", "/images/payment-solutions/use-cases/recharge-dth.jpg", "/images/payment-solutions/use-cases/recharge-portal.jpg"],
    useCases: ["Mobile recharge retailers", "DTH service points", "Digital service portals"],
    eyebrow: "Quick recharges, happy customers",
    headline: "Instant Mobile and DTH Recharge Services",
    description: "Offer prepaid mobile, DTH, and supported recharge services with live operator plans and status tracking.",
    what: "The Recharge solution enables businesses and agents to process everyday mobile and DTH recharges from one interface. Fast validation, operator connectivity, and clear reporting create a dependable experience for customers.",
    benefits: ["Mobile and DTH support", "Operator plan discovery", "Instant recharge status", "Agent commission tracking"],
    steps: ["Customer Selects Service", "Number and Operator Are Added", "Plan Is Selected", "Recharge Is Processed", "Confirmation Is Shared"],
  },
  "credit-card": {
    name: "Credit Card",
    image: "/images/payment-solutions/credit-card.jpg",
    useCaseImages: ["/images/payment-solutions/use-cases/credit-compare.jpg", "/images/payment-solutions/use-cases/credit-leads.jpg", "/images/payment-solutions/use-cases/credit-acquisition.jpg"],
    useCases: ["Card comparison journeys", "Partner lead platforms", "Customer acquisition networks"],
    eyebrow: "Connect customers with the right card",
    headline: "A Simpler Digital Credit Card Journey",
    description: "Enable customers to discover suitable cards and complete an efficient, guided application process.",
    what: "Our Credit Card solution helps businesses present relevant card options and guide eligible customers through the application journey. Structured data collection and status visibility make the process clear for applicants and partners.",
    benefits: ["Multiple card options", "Guided eligibility journey", "Secure lead capture", "Application tracking"],
    steps: ["Customer Explores Cards", "Eligibility Is Checked", "Application Is Completed", "Partner Reviews Request", "Status Is Updated"],
  },
  loans: {
    name: "Loans",
    image: "/images/payment-solutions/services/home-loan.jpg",
    useCaseImages: [loanImages[0], loanImages[1], "/images/payment-solutions/services/loans-assisted-application-networks.png"],
    useCases: ["Digital lending partners", "Business finance portals", "Assisted application networks"],
    eyebrow: "Digital lending made approachable",
    headline: "Connect Customers to Suitable Loan Options",
    description: "Create a guided digital journey for discovering, applying for, and tracking personal and business loan requests.",
    what: "The Loans solution connects eligible customers with lending opportunities through a structured application experience. It simplifies information capture, document collection, partner review, and application tracking without changing lender approval controls.",
    benefits: ["Personal and business options", "Guided eligibility checks", "Secure document collection", "Application status tracking"],
    steps: ["Customer Selects Loan", "Eligibility Is Checked", "Documents Are Submitted", "Lender Reviews Request", "Decision Is Communicated"],
  },
  "cibil-score-check": {
    name: "CIBIL Score Check",
    image: "/images/payment-solutions/services/digital-verification.jpg",
    useCaseImages: ["/images/payment-solutions/services/cibil-loan-eligibility-checks.png", "/images/payment-solutions/services/cibil-credit-counselling.png", verificationImages[2]],
    useCases: ["Loan eligibility checks", "Credit counselling", "Customer onboarding"],
    eyebrow: "Understand creditworthiness quickly",
    headline: "Secure and Convenient CIBIL Score Checks",
    description: "Help customers access their credit score through a guided, consent-based digital journey.",
    what: "CIBIL Score Check enables customers and authorized partners to retrieve credit-score information through a secure verification flow. It supports faster eligibility assessment while keeping customer consent and data privacy central to the experience.",
    benefits: ["Consent-based checks", "Fast score retrieval", "Secure customer data", "Loan-readiness insights"],
    steps: ["Customer Gives Consent", "Identity Details Are Added", "Information Is Verified", "Score Is Retrieved", "Result Is Shared"],
  },
  "pan-verification-otp": {
    name: "PAN Verification with OTP",
    image: "/images/payment-solutions/pan-card.jpg",
    useCaseImages: ["/images/payment-solutions/services/pan-digital-kyc.png", "/images/payment-solutions/services/pan-merchant-onboarding.png", "/images/payment-solutions/services/pan-financial-applications.png"],
    useCases: ["Digital KYC", "Merchant onboarding", "Financial applications"],
    eyebrow: "Verify PAN details securely",
    headline: "Fast PAN Verification with OTP Consent",
    description: "Validate PAN information through a secure OTP-assisted workflow designed for digital onboarding.",
    what: "PAN Verification with OTP helps businesses confirm customer PAN information after explicit OTP authorization. The guided process reduces manual checks and supports reliable identity validation across onboarding journeys.",
    benefits: ["OTP-based consent", "Real-time validation", "Reduced data-entry errors", "API-ready integration"],
    steps: ["PAN Details Are Entered", "OTP Is Requested", "Customer Confirms OTP", "PAN Is Validated", "Result Is Returned"],
  },
  "aadhaar-validation-otp": {
    name: "Aadhaar Validation with OTP",
    image: "/images/payment-solutions/aeps.jpg",
    useCaseImages: ["/images/payment-solutions/services/aadhaar-customer-onboarding.png", "/images/payment-solutions/services/aadhaar-validation-otp-identity-confirmation.png", "/images/payment-solutions/services/aadhaar-validation-otp-assisted-digital-services.png"],
    useCases: ["Customer onboarding", "Identity confirmation", "Assisted digital services"],
    eyebrow: "Consent-led identity validation",
    headline: "Aadhaar Validation through a Secure OTP Flow",
    description: "Support customer identity validation using an OTP-authorized Aadhaar verification journey.",
    what: "Aadhaar Validation with OTP provides a structured way to validate customer identity after consent. It helps authorized businesses streamline onboarding while maintaining clear verification status and audit visibility.",
    benefits: ["Customer consent flow", "OTP authentication", "Faster onboarding", "Clear verification status"],
    steps: ["Aadhaar Details Are Added", "OTP Is Sent", "Customer Enters OTP", "Identity Is Validated", "Status Is Shared"],
  },
  "gstin-verification": {
    name: "GSTIN Verification",
    image: "/images/payment-solutions/pan-card.jpg",
    useCaseImages: ["/images/payment-solutions/services/gstin-verification-business-onboarding.png", "/images/payment-solutions/services/gstin-verification-vendor-verification.png", "/images/payment-solutions/services/gstin-verification-tax-compliance-workflows.png"],
    useCases: ["Business onboarding", "Vendor verification", "Tax-compliance workflows"],
    eyebrow: "Verify businesses with confidence",
    headline: "Instant GSTIN Verification for Business Onboarding",
    description: "Validate GST registration details and improve the accuracy of merchant and vendor onboarding.",
    what: "GSTIN Verification helps businesses confirm registration details against the submitted GSTIN. It supports quicker due diligence, reduces manual data checks, and provides structured results for onboarding workflows.",
    benefits: ["Registration validation", "Business detail checks", "Faster vendor onboarding", "Structured API response"],
    steps: ["GSTIN Is Entered", "Request Is Validated", "Registration Is Checked", "Business Details Are Matched", "Result Is Returned"],
  },
  "bank-verification": {
    name: "Bank Verification",
    image: "/images/payment-solutions/services/digital-verification.jpg",
    useCaseImages: ["/images/payment-solutions/services/bank-verification-beneficiary-onboarding.png", "/images/payment-solutions/services/bank-verification-vendor-payments.png", "/images/payment-solutions/services/bank-verification-refund-validation.png"],
    useCases: ["Beneficiary onboarding", "Vendor payments", "Refund validation"],
    eyebrow: "Confirm accounts before transferring",
    headline: "Reliable Bank Account Verification",
    description: "Validate beneficiary account information before initiating payouts, refunds, or settlements.",
    what: "Bank Verification helps businesses confirm account details before moving funds. The service improves beneficiary accuracy, reduces failed transfers, and adds confidence to payout and onboarding processes.",
    benefits: ["Account detail validation", "Reduced payout failures", "Fast beneficiary checks", "API-led workflow"],
    steps: ["Account Details Are Added", "Verification Is Requested", "Bank Processes Check", "Name Is Matched", "Status Is Returned"],
  },
  "hotel-booking": {
    name: "Hotel Booking",
    image: "/images/payment-solutions/services/hotel-booking.jpg",
    useCaseImages: ["/images/payment-solutions/services/hotel-booking.jpg", "/images/payment-solutions/services/train-booking.jpg", "/images/payment-solutions/services/flight-travel.jpg"],
    useCases: ["Travel agencies", "Corporate travel desks", "Consumer booking portals"],
    eyebrow: "Comfortable stays, simpler booking",
    headline: "Search and Book Hotels from One Platform",
    description: "Offer hotel discovery, room selection, secure payments, and booking confirmation in one journey.",
    what: "Hotel Booking connects travel businesses and customers with searchable accommodation inventory. Users can compare properties, review room options, complete payment, and receive confirmation through a streamlined experience.",
    benefits: ["Broad hotel inventory", "Room and rate comparison", "Secure online payment", "Instant confirmation"],
    steps: ["Destination Is Searched", "Hotel and Room Are Selected", "Guest Details Are Added", "Payment Is Completed", "Voucher Is Issued"],
  },
  "train-booking": {
    name: "Train Booking",
    image: "/images/payment-solutions/services/train-booking.jpg",
    useCaseImages: ["/images/payment-solutions/services/train-booking-authorized-travel-agents.png", "/images/payment-solutions/services/train-booking-assisted-booking-counters.png", "/images/payment-solutions/services/train-booking-travel-service-portals.png"],
    useCases: ["Authorized travel agents", "Assisted booking counters", "Travel service portals"],
    eyebrow: "Rail journeys made easier",
    headline: "Convenient Digital Train Booking Services",
    description: "Enable route search, passenger entry, payment, and ticket-status visibility through an assisted platform.",
    what: "Train Booking gives authorized travel partners a guided workflow for helping customers plan rail journeys. It centralizes search, passenger details, payment status, and booking information for a smoother service experience.",
    benefits: ["Route and schedule search", "Assisted passenger booking", "Secure payment workflow", "Booking status visibility"],
    steps: ["Route Is Searched", "Train Is Selected", "Passenger Details Are Added", "Payment Is Processed", "Booking Status Is Shared"],
  },
  "flight-booking": {
    name: "Flight Booking",
    image: "/images/payment-solutions/services/flight-travel.jpg",
    useCaseImages: ["/images/payment-solutions/services/flight-booking-travel-agencies.png", "/images/payment-solutions/services/flight-booking-business-travel-platforms.png", "/images/payment-solutions/services/flight-booking-consumer-booking-portals.png"],
    useCases: ["Travel agencies", "Business travel platforms", "Consumer booking portals"],
    eyebrow: "Flights at customers' fingertips",
    headline: "Fast Domestic and International Flight Booking",
    description: "Help customers compare flights, select fares, pay securely, and receive booking confirmation.",
    what: "Flight Booking provides a unified journey for searching available flights and completing reservations. Travel businesses can offer fare comparison, passenger management, payment, and confirmation through one digital platform.",
    benefits: ["Flight and fare comparison", "Domestic and international search", "Secure booking payments", "Instant itinerary details"],
    steps: ["Flights Are Searched", "Fare Is Selected", "Traveller Details Are Added", "Payment Is Confirmed", "Itinerary Is Issued"],
  },
  "home-loan": {
    name: "Home Loan",
    image: "/images/payment-solutions/services/home-loan.jpg",
    useCaseImages: ["/images/payment-solutions/services/home-loan-home-buyers.png", "/images/payment-solutions/services/home-loan-loan-marketplaces.png", "/images/payment-solutions/services/home-loan-assisted-finance-partners.png"],
    useCases: ["Home buyers", "Loan marketplaces", "Assisted finance partners"],
    eyebrow: "Make home ownership approachable",
    headline: "A Guided Digital Home Loan Journey",
    description: "Help eligible customers explore home-loan options and submit applications through a structured process.",
    what: "Home Loan supports customers from initial eligibility checks through document submission and lender review. The digital journey improves application clarity while leaving credit decisions with the lending partner.",
    benefits: ["Eligibility guidance", "Multiple lender opportunities", "Secure document collection", "Application tracking"],
    steps: ["Requirement Is Shared", "Eligibility Is Checked", "Documents Are Submitted", "Lender Reviews Application", "Decision Is Communicated"],
  },
  "instant-loan": {
    name: "Instant Loan",
    image: "/images/payment-solutions/services/business-loan.jpg",
    useCaseImages: loanImages,
    useCases: ["Short-term personal needs", "Digital lending platforms", "Assisted finance networks"],
    eyebrow: "Quick access to suitable credit",
    headline: "A Faster Instant Loan Application Experience",
    description: "Guide eligible customers through a quick digital application with secure data and document collection.",
    what: "Instant Loan provides a streamlined application journey for customers seeking fast access to credit. Automated eligibility inputs and structured document collection help lending partners review requests efficiently; approval remains subject to lender policy.",
    benefits: ["Quick eligibility journey", "Simple digital application", "Secure document upload", "Live application tracking"],
    steps: ["Customer Selects Amount", "Eligibility Is Checked", "Application Is Submitted", "Lender Reviews Request", "Decision Is Shared"],
  },
  insurance: {
    name: "Insurance",
    image: "/images/payment-solutions/services/family-insurance.jpg",
    useCaseImages: ["/images/payment-solutions/services/family-insurance.jpg", "/images/payment-solutions/services/health-insurance.jpg", "/images/payment-solutions/services/motor-insurance.jpg"],
    useCases: ["Insurance comparison platforms", "Assisted service agents", "Digital financial marketplaces"],
    eyebrow: "Protection options made accessible",
    headline: "A Simple Digital Insurance Discovery Journey",
    description: "Help customers explore suitable insurance options and submit their details through a guided digital experience.",
    what: "The Insurance solution enables businesses and authorized partners to present relevant protection products and guide interested customers through a structured enquiry or application journey. It simplifies information capture, document collection, partner review, and status updates while product issuance remains subject to the insurer's terms and approval.",
    benefits: ["Multiple insurance categories", "Guided product discovery", "Secure customer data", "Application status visibility"],
    steps: ["Customer Selects Coverage", "Requirements Are Captured", "Suitable Options Are Presented", "Application Is Submitted", "Insurer Shares Decision"],
  },
  "gift-cards-vouchers": {
    name: "Gift Cards & Vouchers",
    image: "/images/payment-solutions/services/gift-vouchers.jpg",
    useCaseImages: ["/images/payment-solutions/services/gift-vouchers.jpg", "/images/payment-solutions/services/family-insurance.jpg", "/images/payment-solutions/services/business-loan.jpg"],
    useCases: ["Employee rewards", "Customer loyalty programs", "Corporate gifting"],
    eyebrow: "Digital rewards made effortless",
    headline: "Gift Cards and Vouchers for Every Occasion",
    description: "Enable businesses and customers to discover, purchase, and distribute digital gift cards and vouchers through one convenient platform.",
    what: "The Gift Cards & Vouchers solution provides a structured digital journey for selecting reward brands, choosing voucher values, completing secure payments, and delivering redemption details. It helps businesses simplify employee recognition, customer rewards, promotional campaigns, and everyday gifting.",
    benefits: ["Multiple brand options", "Instant digital delivery", "Flexible voucher values", "Secure purchase workflow"],
    steps: ["Brand Is Selected", "Voucher Value Is Chosen", "Recipient Details Are Added", "Payment Is Completed", "Voucher Is Delivered"],
  },
  "electricity-bill-payment": createService({
    name: "Electricity Bill Payment", image: "/images/payment-solutions/services/electricity.jpg", useCaseImages: utilityImages,
    useCases: ["Household electricity bills", "Retail payment counters", "Consumer service apps"], eyebrow: "Power bills paid without queues", headline: "Quick and Reliable Electricity Bill Payments",
    description: "Fetch and pay supported electricity bills with secure processing and instant confirmation.", benefits: ["Live bill fetch", "Multiple electricity boards", "Instant confirmation", "Digital receipts"], steps: ["Provider Is Selected", "Consumer Number Is Entered", "Bill Is Fetched", "Payment Is Completed", "Receipt Is Shared"],
  }),
  "water-bill-payment": createService({
    name: "Water Bill Payment", image: "/images/payment-solutions/services/water.jpg", useCaseImages: utilityImages,
    useCases: ["Municipal water bills", "Assisted service outlets", "Digital payment apps"], eyebrow: "Everyday utility payments simplified", headline: "Convenient Online Water Bill Payments",
    description: "Retrieve and pay supported municipal water bills through a simple digital flow.", benefits: ["Supported municipal billers", "Quick bill discovery", "Secure transactions", "Instant receipts"], steps: ["Biller Is Selected", "Account Details Are Added", "Bill Is Retrieved", "Payment Is Processed", "Confirmation Is Shared"],
  }),
  "gas-bill-payment": createService({
    name: "Gas Bill Payment", image: "/images/payment-solutions/services/electricity.jpg", useCaseImages: utilityImages,
    useCases: ["Piped gas bills", "LPG service payments", "Retail agent networks"], eyebrow: "Gas payments in a few simple steps", headline: "Secure Digital Gas Bill Payments",
    description: "Help customers fetch and pay supported gas bills with real-time transaction status.", benefits: ["Multiple gas providers", "Live bill details", "Secure payment options", "Transaction tracking"], steps: ["Gas Provider Is Selected", "Customer ID Is Entered", "Bill Is Fetched", "Payment Is Confirmed", "Receipt Is Generated"],
  }),
  "fastag-recharge": createService({
    name: "FASTag Recharge", image: "/images/payment-solutions/services/motor-insurance.jpg", useCaseImages: utilityImages,
    useCases: ["Private vehicle owners", "Commercial fleets", "Recharge agent portals"], eyebrow: "Keep every journey moving", headline: "Fast and Simple FASTag Recharges",
    description: "Recharge supported FASTag accounts quickly using vehicle or wallet information.", benefits: ["Multiple issuer support", "Instant recharge status", "Fleet-friendly workflow", "Digital confirmation"], steps: ["Issuer Is Selected", "Vehicle Details Are Added", "Amount Is Entered", "Recharge Is Processed", "Status Is Shared"],
  }),
  "broadband-landline-payment": createService({
    name: "Broadband & Landline Payment", image: "/images/payment-solutions/services/broadband.jpg", useCaseImages: utilityImages,
    useCases: ["Home broadband bills", "Business connections", "Assisted payment counters"], eyebrow: "Stay connected without payment delays", headline: "Broadband and Landline Bill Payments",
    description: "Fetch and pay supported broadband and landline bills from one convenient interface.", benefits: ["Broad provider coverage", "Live bill fetch", "Secure payments", "Instant transaction status"], steps: ["Provider Is Selected", "Connection ID Is Added", "Bill Is Retrieved", "Payment Is Completed", "Receipt Is Shared"],
  }),
  "udyam-verification": createService({
    name: "Udyam Verification", image: "/images/payment-solutions/pan-card.jpg", useCaseImages: verificationImages,
    useCases: ["MSME onboarding", "Business lending", "Vendor due diligence"], eyebrow: "Confirm MSME registration details", headline: "Reliable Udyam Registration Verification",
    description: "Validate submitted Udyam registration information for faster business onboarding.", benefits: ["MSME detail validation", "Faster due diligence", "Structured results", "API-ready workflow"], steps: ["Udyam Number Is Entered", "Request Is Validated", "Registration Is Checked", "Details Are Matched", "Result Is Returned"],
  }),
  "cin-verification": createService({
    name: "CIN Verification", image: "/images/payment-solutions/pan-card.jpg", useCaseImages: verificationImages,
    useCases: ["Corporate onboarding", "Vendor verification", "Business compliance checks"], eyebrow: "Verify registered companies quickly", headline: "Digital Corporate Identity Number Verification",
    description: "Confirm company registration information using a submitted Corporate Identity Number.", benefits: ["Company detail checks", "Registration status visibility", "Reduced manual review", "Structured verification output"], steps: ["CIN Is Entered", "Request Is Submitted", "Company Record Is Checked", "Details Are Matched", "Status Is Returned"],
  }),
  "voter-id-verification": createService({
    name: "Voter ID Verification", image: "/images/payment-solutions/pan-card.jpg", useCaseImages: verificationImages,
    useCases: ["Identity onboarding", "Document validation", "Assisted customer verification"], eyebrow: "Support reliable identity checks", headline: "Simple Digital Voter ID Verification",
    description: "Validate submitted Voter ID information through a guided identity-check workflow.", benefits: ["Document detail validation", "Clear verification result", "Faster onboarding", "Secure data handling"], steps: ["Voter ID Is Entered", "Customer Gives Consent", "Record Is Checked", "Details Are Matched", "Result Is Shared"],
  }),
  "personal-loan": createService({
    name: "Personal Loan", image: "/images/payment-solutions/services/home-loan.jpg", useCaseImages: loanImages,
    useCases: ["Personal expenses", "Medical needs", "Debt consolidation"], eyebrow: "Flexible finance for personal goals", headline: "A Guided Personal Loan Application Journey",
    description: "Help eligible customers discover and apply for suitable personal loan options.", benefits: ["Quick eligibility checks", "Multiple lender opportunities", "Secure document collection", "Application tracking"], steps: ["Loan Need Is Selected", "Eligibility Is Checked", "Details Are Submitted", "Lender Reviews Request", "Decision Is Shared"],
  }),
  "business-loan": createService({
    name: "Business Loan", image: "/images/payment-solutions/services/business-loan.jpg", useCaseImages: loanImages,
    useCases: ["Working capital", "Business expansion", "Equipment purchases"], eyebrow: "Capital to support business growth", headline: "Digital Business Loan Applications Made Simple",
    description: "Guide businesses through eligibility, documentation, and lender review for suitable finance options.", benefits: ["Business-focused options", "Guided eligibility", "Secure document upload", "Partner status tracking"], steps: ["Finance Need Is Shared", "Business Eligibility Is Checked", "Documents Are Added", "Lender Reviews Application", "Decision Is Communicated"],
  }),
  "education-loan": createService({
    name: "Education Loan", image: "/images/payment-solutions/services/education-loan.jpg", useCaseImages: loanImages,
    useCases: ["Higher education", "Professional courses", "Overseas studies"], eyebrow: "Finance for learning ambitions", headline: "A Clearer Education Loan Journey",
    description: "Support students and families through a structured education loan application process.", benefits: ["Domestic and overseas options", "Eligibility guidance", "Document checklist", "Application visibility"], steps: ["Course Details Are Shared", "Eligibility Is Reviewed", "Documents Are Submitted", "Lender Evaluates Request", "Decision Is Shared"],
  }),
  "car-loan": createService({
    name: "Car Loan", image: "/images/payment-solutions/services/motor-insurance.jpg", useCaseImages: loanImages,
    useCases: ["New car purchases", "Used car finance", "Vehicle upgrade plans"], eyebrow: "Drive goals forward with suitable finance", headline: "Convenient Digital Car Loan Applications",
    description: "Help eligible customers compare and apply for vehicle finance through a guided workflow.", benefits: ["New and used car options", "Eligibility estimates", "Secure documents", "Application tracking"], steps: ["Vehicle Is Selected", "Eligibility Is Checked", "Application Is Completed", "Lender Reviews Details", "Decision Is Communicated"],
  }),
  "gold-loan": createService({
    name: "Gold Loan", image: "/images/payment-solutions/services/gold-jewelry-hero.jpg", useCaseImages: ["/images/payment-solutions/services/gold-jewelry-hero.jpg", "/images/payment-solutions/services/gold-jewelry-detail.jpg", "/images/payment-solutions/services/gold-jewelry-necklace.jpg"],
    useCases: ["Short-term liquidity", "Business funding", "Emergency expenses"], eyebrow: "Unlock value through a guided process", headline: "Simple Gold Loan Enquiry and Application",
    description: "Connect eligible customers with gold-backed loan opportunities through authorized lending partners.", benefits: ["Quick enquiry flow", "Transparent next steps", "Secure customer details", "Partner status updates"], steps: ["Loan Requirement Is Added", "Basic Eligibility Is Checked", "Gold Assessment Is Scheduled", "Lender Reviews Request", "Offer Is Shared"],
  }),
  "health-insurance": createService({
    name: "Health Insurance", image: "/images/payment-solutions/services/health-insurance.jpg", useCaseImages: ["/images/payment-solutions/services/health-insurance.jpg", "/images/payment-solutions/services/family-insurance.jpg", "/images/payment-solutions/services/motor-insurance.jpg"],
    useCases: ["Individual health cover", "Family protection", "Senior citizen plans"], eyebrow: "Protection for health and wellbeing", headline: "Discover Suitable Health Insurance Options",
    description: "Guide customers through health insurance discovery and application with authorized partners.", benefits: ["Individual and family options", "Guided plan discovery", "Secure information capture", "Application assistance"], steps: ["Coverage Need Is Selected", "Member Details Are Added", "Options Are Presented", "Application Is Submitted", "Insurer Reviews Request"],
  }),
  "life-insurance": createService({
    name: "Life Insurance", image: "/images/payment-solutions/services/family-insurance.jpg", useCaseImages: ["/images/payment-solutions/services/family-insurance.jpg", "/images/payment-solutions/services/health-insurance.jpg", "/images/payment-solutions/services/home-loan.jpg"],
    useCases: ["Family protection", "Term cover discovery", "Long-term financial planning"], eyebrow: "Help protect what matters most", headline: "A Guided Life Insurance Discovery Journey",
    description: "Help customers explore life insurance options aligned with their protection requirements.", benefits: ["Multiple coverage options", "Needs-based guidance", "Secure application details", "Partner status visibility"], steps: ["Protection Need Is Shared", "Customer Details Are Added", "Plans Are Presented", "Application Is Submitted", "Insurer Shares Decision"],
  }),
  "motor-insurance": createService({
    name: "Motor Insurance", image: "/images/payment-solutions/services/motor-insurance.jpg", useCaseImages: ["/images/payment-solutions/services/motor-insurance.jpg", "/images/payment-solutions/services/family-insurance.jpg", "/images/payment-solutions/services/business-loan.jpg"],
    useCases: ["Car insurance", "Two-wheeler insurance", "Policy renewal enquiries"], eyebrow: "Protection for every road journey", headline: "Convenient Motor Insurance Discovery",
    description: "Enable customers to explore motor insurance options and submit vehicle details digitally.", benefits: ["Car and two-wheeler options", "New and renewal journeys", "Secure vehicle data", "Digital application support"], steps: ["Vehicle Details Are Added", "Coverage Is Selected", "Options Are Presented", "Application Is Submitted", "Insurer Confirms Status"],
  }),
  "travel-insurance": createService({
    name: "Travel Insurance", image: "/images/payment-solutions/services/flight-travel.jpg", useCaseImages: ["/images/payment-solutions/services/flight-travel.jpg", "/images/payment-solutions/services/hotel-booking.jpg", "/images/payment-solutions/services/family-insurance.jpg"],
    useCases: ["Domestic trips", "International travel", "Business journeys"], eyebrow: "Travel with greater confidence", headline: "Simple Travel Insurance Applications",
    description: "Help travellers discover suitable protection for domestic and international journeys.", benefits: ["Domestic and international options", "Trip-based coverage", "Secure traveller details", "Fast digital application"], steps: ["Trip Details Are Added", "Traveller Information Is Entered", "Coverage Is Selected", "Application Is Submitted", "Policy Status Is Shared"],
  }),
};

export const paymentSolutionSlugs = Object.keys(paymentSolutionsData);
